# -------- Stage 1: Build --------
FROM node:21-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --prefer-offline --no-audit || \
    npm install --prefer-offline --no-audit

COPY . .

ARG VITE_API_PATH
ENV VITE_API_PATH=$VITE_API_PATH

RUN npm run build


# -------- Stage 2: Production Runtime --------
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
