import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import useAIReport from "../hooks/useAIReport";
import parseAIReport from "../utils/parseAIReport";

export default function AIAnalysisPage() {
  const {
    report,
    loading,
    error,
    refresh,
  } = useAIReport();

  const parsed = report
    ? parseAIReport(report.content)
    : {};

  const getRiskStyles = (risk = "") => {
    const normalizedRisk = risk.toLowerCase();

    if (normalizedRisk.includes("critical")) {
      return "border-red-500/30 bg-red-500/10 text-red-400";
    }

    if (normalizedRisk.includes("high")) {
      return "border-orange-500/30 bg-orange-500/10 text-orange-400";
    }

    if (normalizedRisk.includes("medium")) {
      return "border-yellow-500/30 bg-yellow-500/10 text-yellow-400";
    }

    if (normalizedRisk.includes("low")) {
      return "border-green-500/30 bg-green-500/10 text-green-400";
    }

    return "border-slate-600 bg-slate-800 text-slate-300";
  };

  const getScoreColor = (score) => {
    if (score === null || score === undefined) {
      return "text-slate-400";
    }

    if (score >= 80) {
      return "text-green-400";
    }

    if (score >= 60) {
      return "text-yellow-400";
    }

    if (score >= 40) {
      return "text-orange-400";
    }

    return "text-red-400";
  };

  const formatDate = (date) => {
    if (!date) {
      return "Not available";
    }

    return new Date(date).toLocaleString();
  };

  if (loading) {
    return (
      <div className="flex min-h-[400px] items-center justify-center p-6">
        <div className="text-center">
          <div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-slate-700 border-t-blue-500" />

          <p className="mt-4 text-slate-400">
            Loading Gemini AI security report...
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6">
        <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-6">
          <h2 className="text-xl font-semibold text-red-400">
            Unable to load AI report
          </h2>

          <p className="mt-2 text-slate-300">
            {error}
          </p>

          <button
            type="button"
            onClick={refresh}
            className="mt-5 rounded-lg bg-red-600 px-4 py-2 font-medium text-white transition hover:bg-red-700"
          >
            Try Again
          </button>
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="p-6 text-slate-400">
        No Gemini AI report is available.
      </div>
    );
  }

  return (
    <div className="space-y-6 p-6 text-white">
      {/* Header */}

      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <div className="flex items-center gap-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-600/15 text-2xl">
              🤖
            </div>

            <div>
              <h1 className="text-2xl font-bold sm:text-3xl">
                AI Security Analysis
              </h1>

              <p className="mt-1 text-sm text-slate-400">
                Generated by Google Gemini from Jenkins security artifacts
              </p>
            </div>
          </div>
        </div>

        <button
          type="button"
          onClick={refresh}
          className="rounded-lg bg-blue-600 px-4 py-2 font-medium text-white transition hover:bg-blue-700"
        >
          Refresh Report
        </button>
      </div>

      {/* Build metadata */}

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-5">
          <p className="text-sm text-slate-400">
            Jenkins Build
          </p>

          <p className="mt-2 text-3xl font-bold">
            #{report.buildNumber}
          </p>
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-900 p-5">
          <p className="text-sm text-slate-400">
            Build Result
          </p>

          <p
            className={`mt-2 text-2xl font-bold ${
              report.buildResult === "SUCCESS"
                ? "text-green-400"
                : "text-red-400"
            }`}
          >
            {report.buildResult || "UNKNOWN"}
          </p>
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-900 p-5">
          <p className="text-sm text-slate-400">
            Generated
          </p>

          <p className="mt-2 font-medium text-slate-200">
            {formatDate(report.generatedAt)}
          </p>
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-900 p-5">
          <p className="text-sm text-slate-400">
            Available Reports
          </p>

          <div className="mt-3 grid grid-cols-2 gap-2">
            {report.markdownUrl ? (
              <a
                href={report.markdownUrl}
                target="_blank"
                rel="noreferrer"
                className="rounded-lg bg-blue-600 px-3 py-2 text-center text-sm font-medium transition hover:bg-blue-700"
              >
                Markdown
              </a>
            ) : (
              <button
                type="button"
                disabled
                className="cursor-not-allowed rounded-lg bg-slate-800 px-3 py-2 text-sm text-slate-500"
              >
                Markdown
              </button>
            )}

            {report.htmlUrl ? (
              <a
                href={report.htmlUrl}
                target="_blank"
                rel="noreferrer"
                className="rounded-lg bg-green-600 px-3 py-2 text-center text-sm font-medium transition hover:bg-green-700"
              >
                HTML
              </a>
            ) : (
              <button
                type="button"
                disabled
                className="cursor-not-allowed rounded-lg bg-slate-800 px-3 py-2 text-sm text-slate-500"
              >
                HTML
              </button>
            )}
          </div>
        </div>
      </div>

      {/* AI score and risk */}

      <div className="grid gap-4 lg:grid-cols-2">
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-6">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-sm text-slate-400">
                AI Security Score
              </p>

              <div
                className={`mt-3 text-5xl font-bold ${getScoreColor(
                  parsed.score
                )}`}
              >
                {parsed.score ?? "--"}

                <span className="ml-1 text-xl text-slate-500">
                  /100
                </span>
              </div>
            </div>

            <div className="rounded-xl bg-cyan-500/10 px-3 py-2 text-cyan-400">
              AI
            </div>
          </div>

          <div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-800">
            <div
              className="h-full rounded-full bg-current transition-all duration-500"
              style={{
                width: `${Math.min(
                  Math.max(parsed.score ?? 0, 0),
                  100
                )}%`,
              }}
            />
          </div>

          <p className="mt-3 text-sm text-slate-400">
            Calculated from Gemini analysis of Trivy scan results.
          </p>
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-900 p-6">
          <p className="text-sm text-slate-400">
            Overall Risk Level
          </p>

          <div className="mt-4">
            <span
              className={`inline-flex rounded-lg border px-4 py-2 text-lg font-bold ${getRiskStyles(
                parsed.risk
              )}`}
            >
              {parsed.risk || "Not detected"}
            </span>
          </div>

          <p className="mt-5 text-sm leading-6 text-slate-400">
            Review all critical findings and remediation steps before
            promoting the backend image to production.
          </p>
        </div>
      </div>

      {/* Executive summary */}

      <section className="rounded-xl border border-slate-800 bg-slate-900 p-6">
        <div className="mb-5 flex items-center gap-3">
          <span className="text-2xl">
            📄
          </span>

          <div>
            <h2 className="text-xl font-bold">
              Executive Summary
            </h2>

            <p className="text-sm text-slate-400">
              High-level Gemini assessment of the application security posture
            </p>
          </div>
        </div>

        <div className="prose prose-invert max-w-none prose-p:leading-7 prose-strong:text-white">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {parsed.executiveSummary ||
              "Executive summary was not found in the AI report."}
          </ReactMarkdown>
        </div>
      </section>

      {/* Critical findings */}

      <section className="rounded-xl border border-red-500/20 bg-slate-900 p-6">
        <div className="mb-5 flex items-center gap-3">
          <span className="text-2xl">
            🚨
          </span>

          <div>
            <h2 className="text-xl font-bold text-red-400">
              Critical Findings
            </h2>

            <p className="text-sm text-slate-400">
              Highest-priority vulnerabilities identified by Gemini
            </p>
          </div>
        </div>

        <div className="prose prose-invert max-w-none overflow-x-auto prose-table:w-full prose-th:border prose-th:border-slate-700 prose-th:bg-slate-800 prose-th:p-3 prose-td:border prose-td:border-slate-700 prose-td:p-3 prose-strong:text-white">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {parsed.critical ||
              "No critical vulnerability section was found."}
          </ReactMarkdown>
        </div>
      </section>

      {/* Immediate fixes */}

      <section className="rounded-xl border border-green-500/20 bg-slate-900 p-6">
        <div className="mb-5 flex items-center gap-3">
          <span className="text-2xl">
            🛠️
          </span>

          <div>
            <h2 className="text-xl font-bold text-green-400">
              Immediate Fixes
            </h2>

            <p className="text-sm text-slate-400">
              Recommended remediation plan for the current build
            </p>
          </div>
        </div>

        <div className="prose prose-invert max-w-none prose-pre:overflow-x-auto prose-pre:rounded-lg prose-pre:bg-slate-950 prose-pre:p-4 prose-code:text-cyan-300 prose-strong:text-white">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {parsed.fixes ||
              "No immediate remediation section was found."}
          </ReactMarkdown>
        </div>
      </section>

      {/* Best practices */}

      <section className="rounded-xl border border-blue-500/20 bg-slate-900 p-6">
        <div className="mb-5 flex items-center gap-3">
          <span className="text-2xl">
            🛡️
          </span>

          <div>
            <h2 className="text-xl font-bold text-blue-400">
              DevSecOps Best Practices
            </h2>

            <p className="text-sm text-slate-400">
              Long-term controls recommended by Gemini
            </p>
          </div>
        </div>

        <div className="prose prose-invert max-w-none prose-li:my-2 prose-strong:text-white">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {parsed.bestPractices ||
              "No DevSecOps best-practices section was found."}
          </ReactMarkdown>
        </div>
      </section>

      {/* Full report */}

      <details className="group rounded-xl border border-slate-800 bg-slate-900 p-6">
        <summary className="flex cursor-pointer list-none items-center justify-between">
          <div>
            <h2 className="text-xl font-bold">
              Full Gemini Report
            </h2>

            <p className="mt-1 text-sm text-slate-400">
              Expand to view the complete archived Markdown report
            </p>
          </div>

          <span className="text-2xl text-slate-400 transition group-open:rotate-180">
            ⌄
          </span>
        </summary>

        <div className="prose prose-invert mt-6 max-w-none overflow-x-auto border-t border-slate-800 pt-6 prose-table:w-full prose-th:border prose-th:border-slate-700 prose-th:bg-slate-800 prose-th:p-3 prose-td:border prose-td:border-slate-700 prose-td:p-3 prose-pre:overflow-x-auto prose-pre:bg-slate-950 prose-code:text-cyan-300 prose-strong:text-white">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {report.content}
          </ReactMarkdown>
        </div>
      </details>

      {/* Jenkins build link */}

      {report.buildUrl && (
        <div className="flex justify-end">
          <a
            href={report.buildUrl}
            target="_blank"
            rel="noreferrer"
            className="text-sm font-medium text-blue-400 transition hover:text-blue-300"
          >
            Open Jenkins Build #{report.buildNumber} →
          </a>
        </div>
      )}
    </div>
  );
}
