services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    image: pratikrangari/wanderlust-backend:latest
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile_optimized
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/wanderlust
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    image: pratikrangari/wanderlust-frontend:latest
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile_optimized
      args:
        VITE_API_PATH: http://localhost:5000
    ports:
      - "5173:80"
    depends_on:
      - backend
